### PR TITLE
Fix test suite failure when no tf wheel

### PR DESCRIPTION
**Pull request by MattToast**
Resolves test module `test_dbmodel.py` using symbols from a TF import statement that may not be present at test time (e.g. if a user installs w/o ml backends and then runs `make test-full`)

### CODE REVIEW

**Review by mellis13 — APPROVED** [review]
LGTM -- thanks for fixing this

**Review by mellis13 — APPROVED** [review]
LGTM -- thanks for fixing this

**Comment by mellis13** [comment]
Just a quick question on this -- is it worth noting in the change log that we fixed this bug?

**Comment by MattToast** [comment]
> Just a quick question on this -- is it worth noting in the change log that we fixed this bug?

Certainly couldn't hurt in case anyone user was running into this issue. I'll throw in a quick mention

**Pull request merged**
